platform :ios, '9.0'

target 'LewisKendrick_KeenFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LewisKendrick_KeenFit

pod ‘Firebase/Core’

end
